/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'caoqifa' at '18-10-29 下午3:20' with Gradle 2.14.1
 *
 * @author caoqifa, @date 18-10-29 下午3:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
